// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BUB",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "BUB",
            targets: ["AppModule"],
            bundleIdentifier: "chotiwat.BUB",
            teamIdentifier: "4U9722GKHJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .speechRecognition(purposeString: "To convert your voice to text for processing your bus route."),
                .microphone(purposeString: "Microphone is used to record your destination using your voice.")
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)